<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'estado_general',
		'conciente',		
		'alerta',
		'hidratado',
		array('label'=>'Cabeza',
			'value'=>$model->idCaracteristicasFisicas->cabeza),
		array('label'=>'Ojos',
			'value'=>$model->idCaracteristicasFisicas->ojos),
		array('label'=>'ORL',
			'value'=>$model->idCaracteristicasFisicas->orl),
		array('label'=>'Cuello',
			'value'=>$model->idCaracteristicasFisicas->cuello),
		array('label'=>'CP',
			'value'=>$model->idCaracteristicasFisicas->cp),
		array('label'=>'Abdomen',
			'value'=>$model->idCaracteristicasFisicas->abdomen),
		array('label'=>'Osteoarticular',
			'value'=>$model->idCaracteristicasFisicas->osteoarticular),
		array('label'=>'Muscular',
			'value'=>$model->idCaracteristicasFisicas->muscular),
		array('label'=>'Piel faneras',
			'value'=>$model->idCaracteristicasFisicas->piel_faneras),
		array('label'=>'Postura',
			'value'=>$model->idCaracteristicasFisicas->postura),
		array('label'=>'TA',
			'value'=>$model->idMedidasFisicas->ta),
		array('label'=>'FC',
			'value'=>$model->idMedidasFisicas->fc),
		array('label'=>'FR',
			'value'=>$model->idMedidasFisicas->fr),
		array('label'=>'Peso',
			'value'=>$model->idMedidasFisicas->peso),
		array('label'=>'Talla',
			'value'=>$model->idMedidasFisicas->talla),
		array('label'=>'IMC',
			'value'=>$model->idMedidasFisicas->imc),
		array('label'=>'Peso ideal',
			'value'=>$model->idMedidasFisicas->peso_ideal),
		array('label'=>'Gasto basal energetico',
			'value'=>$model->idMedidasFisicas->gasto_basal_energia),
		'observaciones'
	),
)); ?>